# Generated by Django 5.2.4 on 2026-02-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0006_review'),
        ('payments', '0002_owneronlinepayment'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymRevenue',
            fields=[
                ('revenue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revenue_type', models.CharField(choices=[('booking', 'Booking'), ('tournament', 'Tournament')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='payments.bookingpayment')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='gyms.gym')),
                ('tournament_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Gym Revenue',
                'verbose_name_plural': 'Gym Revenues',
                'db_table': 'gym_revenues',
            },
        ),
    ]
