# Generated by Django 6.0.2 on 2026-03-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0007_gymimage'),
        ('payments', '0002_owneronlinepayment'),
        ('revenues', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking_payment__isnull', False), ('revenue_type', 'booking'), ('tournament_payment__isnull', True)), models.Q(('booking_payment__isnull', True), ('revenue_type', 'tournament'), ('tournament_payment__isnull', False)), _connector='OR'), name='gymrevenue_revenue_type_payment_constraint'),
        ),
    ]
