# Generated by Django 5.2.4 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0002_gymrevenue_gymrevenue_revenue_type_payment_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.UniqueConstraint(
                condition=models.Q(booking_payment__isnull=False),
                fields=('booking_payment',),
                name='gymrevenue_unique_booking_payment',
            ),
        ),
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.UniqueConstraint(
                condition=models.Q(tournament_payment__isnull=False),
                fields=('tournament_payment',),
                name='gymrevenue_unique_tournament_payment',
            ),
        ),
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gte=0),
                name='gymrevenue_amount_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.CheckConstraint(
                condition=models.Q(commission_amount__gte=0),
                name='gymrevenue_commission_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.CheckConstraint(
                condition=models.Q(net_amount__gte=0),
                name='gymrevenue_net_non_negative',
            ),
        ),
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.CheckConstraint(
                condition=models.Q(net_amount=models.F('amount') - models.F('commission_amount')),
                name='gymrevenue_net_amount_formula',
            ),
        ),
        migrations.AddConstraint(
            model_name='gymrevenue',
            constraint=models.CheckConstraint(
                condition=models.Q(status='completed'),
                name='gymrevenue_status_completed_only',
            ),
        ),
    ]
