# Generated by Django 5.2.12 on 2026-04-21 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_bookingpayment_confirmation_email_delivery_state'),
        ('revenues', '0004_tournament_revenue_payment_traceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymrevenue',
            name='tournament_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='payments.tournamentpayment'),
        ),
    ]
