"""
Django settings for project_confic project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import environ
import importlib.util
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except ImportError:
    def load_dotenv(*args, **kwargs):
        return False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Initialise environment
env = environ.Env(
    DEBUG=(bool, False),
)

# Staging/production intent flag (used for sensible defaults).
# This allows you to keep `DEBUG`/hardening behavior aligned with environment without adding new settings modules.
APP_ENV = (env('APP_ENV', default='development') or '').strip().lower()

# Read .env file if present (do not require committed secrets).
_env_file = os.path.join(BASE_DIR, '.env')
if os.path.exists(_env_file):
    environ.Env.read_env(_env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('DEBUG') is None:
    # If DEBUG is not explicitly set, infer it from APP_ENV.
    DEBUG = APP_ENV not in {'staging', 'production'}
else:
    DEBUG = env.bool('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# - Set SECRET_KEY in `.env` or the environment for all non-toy deployments.
# - When DEBUG=True, a fixed development-only fallback is used if SECRET_KEY is unset
#   (stable JWT signing across restarts on localhost). Never rely on this when DEBUG=False.
_secret_key = (env('SECRET_KEY', default='') or '').strip()
if not _secret_key:
    if DEBUG:
        _secret_key = 'django-insecure-dev-only-set-SECRET_KEY-in-env-for-non-local-use'
    else:
        raise ImproperlyConfigured(
            'SECRET_KEY must be set when DEBUG is False. '
            'Add SECRET_KEY to your environment or .env file.'
        )
SECRET_KEY = _secret_key

# Comma-separated hosts, e.g. "api.example.com,localhost"
# Include "testserver" by default to keep Django test client requests working.

_DEFAULT_ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.99.149.243', 'testserver']

if not DEBUG and os.getenv('ALLOWED_HOSTS') is None:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be set when DEBUG is False.')
ALLOWED_HOSTS = [
    host.strip()
    for host in env.list('ALLOWED_HOSTS', default=_DEFAULT_ALLOWED_HOSTS)
    if host.strip()
]
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must not be empty when DEBUG is False.')

# Trusted origins (CSRF) for deployments behind a real domain.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'apps.users',
    'apps.gyms',
    'apps.bookings',
    'apps.payments',
    'apps.expenses',
    'apps.tournaments',
    'apps.revenues',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'project_confic.middleware.request_id.RequestIdMiddleware',
    'project_confic.middleware.api_deprecation.ApiDeprecationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


def _module_available(module_name: str) -> bool:
    return importlib.util.find_spec(module_name) is not None


if _module_available('corsheaders'):
    INSTALLED_APPS.insert(INSTALLED_APPS.index('django.contrib.staticfiles') + 1, 'corsheaders')
    # CORS middleware must be high enough to add headers to responses.
    MIDDLEWARE.insert(MIDDLEWARE.index('django.middleware.common.CommonMiddleware'), 'corsheaders.middleware.CorsMiddleware')

if _module_available('whitenoise'):
    # WhiteNoise should run immediately after SecurityMiddleware.
    MIDDLEWARE.insert(MIDDLEWARE.index('django.contrib.sessions.middleware.SessionMiddleware'), 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'project_confic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_confic.wsgi.application'
ASGI_APPLICATION = 'project_confic.asgi.application'


# Database
# Prefer explicit DB_* variables for clarity, while still allowing DATABASE_URL override.
# Examples:
# - postgres://user:pass@host:5432/dbname
DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=(
            f"postgres://"
            f"{env('DB_USER', default='postgres')}:"
            f"{env('DB_PASSWORD', default='Ahmadi123')}@"
            f"{env('DB_HOST', default='localhost')}:"
            f"{env('DB_PORT', default='5432')}/"
            f"{env('DB_NAME', default='futsaldb')}"
        ),
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kabul'

USE_I18N = True

LANGUAGES = [
    ('en', 'English'),
    ('ps', 'Pashto'),
    ('fa', 'Dari'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if _module_available('whitenoise'):
    STORAGES = {
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# CORS (keep strict by default; allow configuring explicitly)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.users.authentication.VerifiedUserJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/minute',
    },
    'DEFAULT_PAGINATION_CLASS': 'apps.common.api.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'apps.common.api.standard_exception_handler',
}

# Security hardening (env-driven; safe defaults keep local dev working)
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_REFERRER_POLICY = env('SECURE_REFERRER_POLICY', default='same-origin')
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# When running behind a TLS-terminating proxy/load balancer, set this env var:
# USE_X_FORWARDED_PROTO=true
USE_X_FORWARDED_PROTO = env.bool('USE_X_FORWARDED_PROTO', default=False)
if USE_X_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Logging (console-first; safe for production, avoids secret leakage)
LOG_LEVEL = env('LOG_LEVEL', default='INFO')
# Keep request id extraction configurable for future deployments behind different gateways.
REQUEST_ID_HEADER = env('REQUEST_ID_HEADER', default='X-Request-ID')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'project_confic.log_filters.RequestIdFilter',
        },
    },
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s [%(request_id)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'filters': ['request_id'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps.payments': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Stripe (TEST MODE, env-only)
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')  # validated at runtime by payments module
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')  # validated at runtime by payments module
STRIPE_CURRENCY = env('STRIPE_CURRENCY', default='AFN')
BOOKING_PENDING_EXPIRY_MINUTES = env.int('BOOKING_PENDING_EXPIRY_MINUTES', default=20)
BOOKING_LIFECYCLE_SCHEDULE_SECONDS = env.int('BOOKING_LIFECYCLE_SCHEDULE_SECONDS', default=60)
BOOKING_LIFECYCLE_MAX_STALENESS_SECONDS = env.int('BOOKING_LIFECYCLE_MAX_STALENESS_SECONDS', default=300)
ENABLE_LEGACY_API_ROUTES = env.bool('ENABLE_LEGACY_API_ROUTES', default=False)

# Email (SMTP via environment variables only)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').replace(' ', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER).strip()
EMAIL_TIMEOUT = 10

# NOTE: Do not hard-fail at import time for missing/invalid Stripe secrets.
# The payments module returns 503 with a sanitized error message when misconfigured.

