# Generated by Django 6.0.2 on 2026-03-29

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_owneronlinepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneronlinepayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bookingpayment',
            constraint=models.UniqueConstraint(
                condition=Q(payment_status='pending'),
                fields=('booking',),
                name='bookingpayment_single_pending_per_booking',
            ),
        ),
        migrations.AddConstraint(
            model_name='bookingpayment',
            constraint=models.UniqueConstraint(
                condition=Q(payment_status='success'),
                fields=('booking',),
                name='bookingpayment_single_success_per_booking',
            ),
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
    ]
