# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0012_unique_review_per_user_per_gym"),
        ("tournaments", "0004_team_confirmed_status"),
        ("users", "0001_initial"),
        ("payments", "0003_payment_integrity_and_webhook_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentPayment",
            fields=[
                ("tournament_payment_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="AFN", max_length=10)),
                ("payment_gateway", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_payments",
                        to="gyms.gym",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_payments",
                        to="users.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="tournaments.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Payment",
                "verbose_name_plural": "Tournament Payments",
                "db_table": "tournament_payments",
                "ordering": ["-created_at"],
            },
        ),
    ]

