# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_tournamentpayment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tournamentpayment",
            constraint=models.UniqueConstraint(
                condition=Q(payment_status="pending"),
                fields=("tournament", "team", "payer"),
                name="tournamentpayment_single_pending_per_registration",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentpayment",
            constraint=models.UniqueConstraint(
                condition=Q(payment_status="success"),
                fields=("tournament", "team", "payer"),
                name="tournamentpayment_single_success_per_registration",
            ),
        ),
    ]

