# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_tournamentpayment_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tournamentpayment",
            constraint=models.UniqueConstraint(
                condition=Q(payment_status="pending") & Q(team__isnull=True),
                fields=("tournament", "payer"),
                name="tournamentpayment_single_pending_per_tournament_when_no_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentpayment",
            constraint=models.UniqueConstraint(
                condition=Q(payment_status="success") & Q(team__isnull=True),
                fields=("tournament", "payer"),
                name="tournamentpayment_single_success_per_tournament_when_no_team",
            ),
        ),
    ]

