# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_tournamentpayment_null_team_constraints"),
        ("tournaments", "0004_team_confirmed_status"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentStripeWebhookAudit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("payment_intent_id", models.CharField(db_index=True, max_length=255)),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournament_stripe_webhook_audits",
                        to="users.user",
                    ),
                ),
                (
                    "stripe_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_audit",
                        to="payments.stripewebhookevent",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_webhook_audits",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "tournament_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_webhook_audits",
                        to="payments.tournamentpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Stripe Webhook Audit",
                "verbose_name_plural": "Tournament Stripe Webhook Audits",
                "db_table": "tournament_stripe_webhook_audits",
                "ordering": ["-created_at"],
            },
        ),
    ]

