# Generated by Django 6.0.2 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_tournament_stripe_webhook_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentpayment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tournamentpayment",
            name="purpose",
            field=models.CharField(
                choices=[("registration", "Tournament registration")],
                default="registration",
                max_length=30,
            ),
        ),
    ]

