import {
  TOURNAMENT_STATUS,
  adaptMatch,
  adaptStandings,
  normalizeTournamentStatus,
} from "../utils/tournamentMapper";

export const createDefaultGroups = () => ({
  groupA: [],
  groupB: [],
});

export const getTournamentMatches = (tournament) => {
  const groupMatches = Array.isArray(tournament?.groupMatches)
    ? tournament.groupMatches.map(adaptMatch).filter(Boolean)
    : [];
  const knockoutMatches = Array.isArray(tournament?.knockoutMatches)
    ? tournament.knockoutMatches.map(adaptMatch).filter(Boolean)
    : [];

  return {
    groupMatches,
    knockoutMatches,
    allMatches: [...groupMatches, ...knockoutMatches],
  };
};

export const assignTeamToGroup = (groups, team) => {
  const groupACount = groups.groupA.length;
  const groupBCount = groups.groupB.length;
  if (groupACount <= groupBCount) {
    return { ...groups, groupA: [...groups.groupA, team] };
  }
  return { ...groups, groupB: [...groups.groupB, team] };
};

// TODO: replace with backend-generated group matches.
export const generateGroupMatches = (teams, groupName, existingMatches = []) => {
  const matches = [];
  const existingIds = existingMatches.map(
    (match) => `${match.team1Id}_${match.team2Id}`,
  );
  for (let i = 0; i < teams.length; i += 1) {
    for (let j = i + 1; j < teams.length; j += 1) {
      const matchKey1 = `${teams[i].id}_${teams[j].id}`;
      const matchKey2 = `${teams[j].id}_${teams[i].id}`;
      if (existingIds.includes(matchKey1) || existingIds.includes(matchKey2)) {
        continue;
      }
      matches.push({
        id: `match_${groupName}_${Date.now()}_${i}_${j}`,
        team1Id: teams[i].id,
        team2Id: teams[j].id,
        team1Name: teams[i].captainName,
        team2Name: teams[j].captainName,
        group: groupName,
        status: "scheduled",
        score1: null,
        score2: null,
        winner: null,
        loser: null,
        isDraw: false,
        round: "Group Stage",
        isAutoGenerated: true,
      });
    }
  }
  return matches;
};

// TODO: replace with backend standings endpoint.
export const calculateStandings = (teams, matches, groupName) => {
  const groupMatches = matches.filter(
    (match) => match.group === groupName && match.status === "completed",
  );
  const standings = teams.map((team) => {
    const teamMatches = groupMatches.filter(
      (match) => match.team1Id === team.id || match.team2Id === team.id,
    );
    let points = 0;
    let wins = 0;
    let draws = 0;
    let losses = 0;
    let goalsFor = 0;
    let goalsAgainst = 0;
    const played = teamMatches.length;

    teamMatches.forEach((match) => {
      const isTeam1 = match.team1Id === team.id;
      const score1 = isTeam1 ? match.score1 : match.score2;
      const score2 = isTeam1 ? match.score2 : match.score1;
      goalsFor += score1 || 0;
      goalsAgainst += score2 || 0;
      if (match.isDraw) {
        draws += 1;
        points += 1;
      } else if (match.winner === team.id) {
        wins += 1;
        points += 3;
      } else {
        losses += 1;
      }
    });

    return {
      teamId: team.id,
      teamName: team.captainName,
      played,
      wins,
      draws,
      losses,
      goalsFor,
      goalsAgainst,
      goalDifference: goalsFor - goalsAgainst,
      points,
    };
  });

  return standings.sort((a, b) => {
    if (b.points !== a.points) {
      return b.points - a.points;
    }
    if (b.goalDifference !== a.goalDifference) {
      return b.goalDifference - a.goalDifference;
    }
    return b.goalsFor - a.goalsFor;
  });
};

export const getTopTeams = (standings, count = 2) => standings.slice(0, count);

// TODO: replace with backend knockout/bracket endpoints.
export const generateKnockoutMatches = (
  groupAQualifiers,
  groupBQualifiers,
  existingKnockoutMatches = [],
  options = {},
) => {
  if (groupAQualifiers.length < 2 || groupBQualifiers.length < 2) {
    return existingKnockoutMatches;
  }

  const variant = options.variant || "list";
  const newMatches = [];
  const existingIds = existingKnockoutMatches.map((match) => match.id);

  if (variant === "owner") {
    const match1Id = "knockout_final";
    if (!existingIds.includes(match1Id)) {
      newMatches.push({
        id: match1Id,
        team1Id: groupAQualifiers[0].teamId,
        team2Id: groupBQualifiers[0].teamId,
        team1Name: groupAQualifiers[0].teamName,
        team2Name: groupBQualifiers[0].teamName,
        round: "Final",
        knockoutPosition: 1,
        status: "scheduled",
        winner: null,
        loser: null,
        isDraw: false,
      });
    }

    const match2Id = "knockout_semifinal";
    if (!existingIds.includes(match2Id)) {
      newMatches.push({
        id: match2Id,
        team1Id: groupAQualifiers[1].teamId,
        team2Id: groupBQualifiers[1].teamId,
        team1Name: groupAQualifiers[1].teamName,
        team2Name: groupBQualifiers[1].teamName,
        round: "Semi-Final",
        knockoutPosition: 2,
        status: "scheduled",
        winner: null,
        loser: null,
        isDraw: false,
      });
    }

    const match3Id = "knockout_challenge";
    if (!existingIds.includes(match3Id)) {
      newMatches.push({
        id: match3Id,
        team1Id: null,
        team2Id: null,
        team1Name: "TBD",
        team2Name: "TBD",
        round: "Challenge Match",
        knockoutPosition: 3,
        status: "scheduled",
        dependsOn: [match2Id, match1Id],
        winner: null,
        loser: null,
        isDraw: false,
      });
    }

    return [...existingKnockoutMatches, ...newMatches];
  }

  const match1Id = "knockout_final";
  if (!existingIds.includes(match1Id)) {
    newMatches.push({
      id: match1Id,
      team1Id: groupAQualifiers[0].teamId,
      team2Id: groupBQualifiers[0].teamId,
      team1Name: groupAQualifiers[0].teamName,
      team2Name: groupBQualifiers[0].teamName,
      round: "Final (A1 vs B1)",
      knockoutPosition: 1,
      status: "scheduled",
      winner: null,
      loser: null,
      isDraw: false,
    });
  }

  const match2Id = "knockout_semifinal";
  if (!existingIds.includes(match2Id)) {
    newMatches.push({
      id: match2Id,
      team1Id: groupAQualifiers[1].teamId,
      team2Id: groupBQualifiers[1].teamId,
      team1Name: groupAQualifiers[1].teamName,
      team2Name: groupBQualifiers[1].teamName,
      round: "Semi-Final (A2 vs B2)",
      knockoutPosition: 2,
      status: "scheduled",
      winner: null,
      loser: null,
      isDraw: false,
    });
  }

  const match3Id = "knockout_thirdplace";
  if (!existingIds.includes(match3Id)) {
    newMatches.push({
      id: match3Id,
      team1Id: null,
      team2Id: null,
      team1Name: "Winner Semi-Final",
      team2Name: "Final Loser",
      round: "Third Place Playoff",
      knockoutPosition: 3,
      status: "pending",
      dependsOn: [match2Id, match1Id],
      winner: null,
      loser: null,
      isDraw: false,
    });
  }

  return [...existingKnockoutMatches, ...newMatches];
};

// TODO: replace with backend ranking endpoint.
export const generateFinalRanking = (
  groupATeams,
  groupBTeams,
  groupAStandings,
  groupBStandings,
  knockoutMatches,
  options = {},
) => {
  const variant = options.variant || "list";
  const ranking = [];
  const completedKnockout = knockoutMatches.filter(
    (match) => match.status === "completed",
  );

  if (variant === "owner") {
    const championMatch = completedKnockout.find(
      (match) => match.round === "Final" || match.round === "Match 1",
    );
    const champion = championMatch?.winner || null;
    const challengeMatch = completedKnockout.find(
      (match) =>
        match.round === "Challenge Match" || match.round === "Third Place",
    );
    const runnerUp = challengeMatch?.winner || championMatch?.loser || null;
    const semiFinalMatch = completedKnockout.find(
      (match) =>
        match.round === "Semi-Final" ||
        match.round === "Semi-Final 1" ||
        match.round === "Semi-Final 2" ||
        match.round === "Match 2",
    );
    const semiFinalWinner = semiFinalMatch?.winner || null;
    const semiFinalLoser = semiFinalMatch?.loser || null;
    const thirdPlace = challengeMatch?.loser || semiFinalWinner || null;
    const allTeams = [...(groupATeams || []), ...(groupBTeams || [])];

    for (let i = 0; i < allTeams.length; i += 1) {
      const team = allTeams[i];
      const isChampion = champion === team.id;
      const isRunnerUp = runnerUp === team.id;
      const isThirdPlace = thirdPlace === team.id;
      const isSemiFinalWinner = semiFinalWinner === team.id;
      const isSemiFinalLoser = semiFinalLoser === team.id;

      let position;
      if (isChampion) position = 1;
      else if (isRunnerUp) position = 2;
      else if (isThirdPlace) position = 3;
      else if (isSemiFinalWinner) position = 4;
      else if (isSemiFinalLoser) position = 5;
      else {
        const groupAStanding = groupAStandings.find(
          (standing) => standing.teamId === team.id,
        );
        const groupBStanding = groupBStandings.find(
          (standing) => standing.teamId === team.id,
        );
        if (groupAStanding) position = 6 + groupAStandings.indexOf(groupAStanding);
        else if (groupBStanding) position = 6 + groupBStandings.indexOf(groupBStanding);
        else position = 6 + i;
      }

      ranking.push({
        position,
        teamId: team.id,
        teamName: team.captainName,
      });
    }

    return ranking.sort((a, b) => a.position - b.position);
  }

  const champion = completedKnockout.find(
    (match) => match.knockoutPosition === 1,
  )?.winner;
  const runnerUp = completedKnockout.find(
    (match) => match.knockoutPosition === 1,
  )?.loser;
  const semiFinalWinner = completedKnockout.find(
    (match) => match.knockoutPosition === 2,
  )?.winner;
  const semiFinalLoser = completedKnockout.find(
    (match) => match.knockoutPosition === 2,
  )?.loser;
  const allTeams = [...(groupATeams || []), ...(groupBTeams || [])];

  for (let i = 0; i < allTeams.length; i += 1) {
    const team = allTeams[i];
    const isChampion = champion === team.id;
    const isRunnerUp = runnerUp === team.id;
    const isSemiFinalWinner = semiFinalWinner === team.id;
    const isSemiFinalLoser = semiFinalLoser === team.id;

    let position;
    if (isChampion) position = 1;
    else if (isRunnerUp) position = 2;
    else if (isSemiFinalWinner) position = 3;
    else if (isSemiFinalLoser) position = 4;
    else {
      const groupAStanding = groupAStandings.find(
        (standing) => standing.teamId === team.id,
      );
      const groupBStanding = groupBStandings.find(
        (standing) => standing.teamId === team.id,
      );
      if (groupAStanding) position = 5 + groupAStandings.indexOf(groupAStanding);
      else if (groupBStanding) position = 5 + groupBStandings.indexOf(groupBStanding);
      else position = 5 + i;
    }

    ranking.push({
      position,
      teamId: team.id,
      teamName: team.captainName,
    });
  }

  return ranking.sort((a, b) => a.position - b.position);
};

export const normalizeUiTournamentStatus = normalizeTournamentStatus;
export { TOURNAMENT_STATUS, adaptStandings };

export default {
  TOURNAMENT_STATUS,
  createDefaultGroups,
  getTournamentMatches,
  assignTeamToGroup,
  generateGroupMatches,
  calculateStandings,
  getTopTeams,
  generateKnockoutMatches,
  generateFinalRanking,
  normalizeUiTournamentStatus,
  adaptStandings,
};
