# Generated by Django 5.2.4 on 2026-02-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='Day of week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='gyms.field')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'time_slots',
            },
        ),
    ]
