# Generated by Django 5.2.4 on 2026-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('futsal', 'futsal'), ('football', 'football'), ('both', 'Both')], default='futsal', max_length=20),
        ),
    ]
