# Generated by Django 5.2.4 on 2026-02-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymImage',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gyms.gym')),
            ],
            options={
                'verbose_name': 'Gym Image',
                'verbose_name_plural': 'Gym Images',
                'db_table': 'gym_images',
            },
        ),
    ]
