# Generated by Cursor on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0010_gym_is_deleted_gymauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.UniqueConstraint(
                condition=models.Q(code__isnull=False) & ~models.Q(code=""),
                fields=("gym", "code"),
                name="unique_discount_code_per_gym_when_present",
            ),
        ),
    ]

