# Generated by Cursor on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0011_discount_code_support"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "gym"),
                name="unique_review_per_user_per_gym",
            ),
        ),
    ]

