# Generated by Django 5.2.12 on 2026-04-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_email_auth_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationotp',
            new_name='email_verif_email_9d7c87_idx',
            old_name='email_verif_email_7d3f4e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationotp',
            new_name='email_verif_user_id_221112_idx',
            old_name='email_verif_user_id_72ce2f_idx',
        ),
    ]
