# Generated by Django 5.2.4 on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(
                choices=[('registered', 'Registered'), ('eliminated', 'Eliminated')],
                default='registered',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='tournament',
            name='champion_team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='champion_for_tournaments',
                to='tournaments.team',
            ),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(
                condition=models.Q(end_time__gt=models.F('start_time')),
                name='match_end_time_after_start_time',
            ),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(
                condition=~models.Q(team1=models.F('team2')),
                name='match_teams_must_be_different',
            ),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(
                condition=models.Q(winner_team__isnull=True)
                | models.Q(winner_team=models.F('team1'))
                | models.Q(winner_team=models.F('team2')),
                name='match_winner_must_be_participant',
            ),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(
                fields=('field', 'match_date', 'start_time'),
                name='unique_field_match_start_slot',
            ),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(
                fields=('tournament', 'captain_phone'),
                name='unique_team_captain_phone_per_tournament',
            ),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(
                fields=('tournament', 'team_name'),
                name='unique_team_name_per_tournament',
            ),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(
                condition=models.Q(end_date__gte=models.F('start_date')),
                name='tournament_end_date_after_start_date',
            ),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(
                condition=models.Q(max_teams__gte=2),
                name='tournament_max_teams_gte_2',
            ),
        ),
    ]
