# Generated by Cursor on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0003_lifecycle_and_result_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("confirmed", "Confirmed"),
                    ("eliminated", "Eliminated"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
    ]

