# Generated by Codex on 2026-04-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0004_team_confirmed_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("pending_owner_approval", "Pending Owner Approval"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("eliminated", "Eliminated"),
                ],
                default="registered",
                max_length=30,
            ),
        ),
    ]
