# Generated by Django 5.2.12 on 2026-04-21 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_unique_review_per_user_per_gym'),
        ('tournaments', '0005_team_owner_approval_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tournament Group',
                'verbose_name_plural': 'Tournament Groups',
                'db_table': 'tournament_groups',
                'ordering': ['order', 'group_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date', 'start_time', 'stage_order', 'match_id'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['created_at', 'team_id'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='played_match_requires_scores_and_winner',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='played_match_cannot_have_draw',
        ),
        migrations.RemoveConstraint(
            model_name='tournament',
            name='tournament_max_teams_gte_2',
        ),
        migrations.RemoveConstraint(
            model_name='tournament',
            name='tournament_finished_requires_champion',
        ),
        migrations.RemoveConstraint(
            model_name='tournament',
            name='tournament_non_finished_requires_null_champion',
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('group', 'Group Stage'), ('knockout_match_1', 'Knockout Match 1'), ('knockout_match_2', 'Knockout Match 2'), ('knockout_match_3', 'Knockout Match 3')], default='group', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='stage_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='runner_up_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_for_tournaments', to='tournaments.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('pending_owner_approval', 'Pending Owner Approval'), ('confirmed', 'Confirmed'), ('eliminated', 'Eliminated'), ('rejected', 'Rejected')], default='registered', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('max_teams__gte', 4)), name='tournament_max_teams_gte_4'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('champion_team__isnull', False), ('runner_up_team__isnull', False), ('status', 'finished')), models.Q(('status', 'finished'), _negated=True), _connector='OR'), name='tournament_finished_requires_ranked_top_two'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'finished'), models.Q(('champion_team__isnull', True), ('runner_up_team__isnull', True)), _connector='OR'), name='tournament_non_finished_requires_null_top_two'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('champion_team__isnull', True), ('runner_up_team__isnull', True), models.Q(('champion_team', models.F('runner_up_team')), _negated=True), _connector='OR'), name='tournament_top_two_must_be_distinct'),
        ),
        migrations.AddField(
            model_name='tournamentgroup',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentgroup'),
        ),
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='tournaments.tournamentgroup'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('stage', 'group')), models.Q(('stage', 'group'), _negated=True), _connector='OR'), name='group_match_requires_group'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('stage', 'group'), ('group__isnull', True), _connector='OR'), name='knockout_match_requires_null_group'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('stage', 'group'), _negated=True), fields=('tournament', 'stage'), name='unique_knockout_stage_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('stage', 'group')), fields=('tournament', 'group', 'team1', 'team2'), name='unique_group_match_pair_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'played'), ('team1_score__isnull', False), ('team2_score__isnull', False)), models.Q(('status', 'played'), _negated=True), _connector='OR'), name='played_match_requires_scores'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'group'), ('status', 'played')), models.Q(('status', 'played'), ('winner_team__isnull', False)), models.Q(('status', 'played'), _negated=True), _connector='OR'), name='played_knockout_match_requires_winner'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'group'), ('status', 'played')), models.Q(('status', 'played'), ('team1_score__gt', models.F('team2_score'))), models.Q(('status', 'played'), ('team2_score__gt', models.F('team1_score'))), models.Q(('status', 'played'), _negated=True), _connector='OR'), name='played_knockout_match_cannot_have_draw'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('final_rank__isnull', False)), fields=('tournament', 'final_rank'), name='unique_team_final_rank_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentgroup',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_group_name_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentgroup',
            constraint=models.UniqueConstraint(fields=('tournament', 'order'), name='unique_group_order_per_tournament'),
        ),
    ]
