# Generated by Django 5.2.4 on 2026-02-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ticket'),
        ('gyms', '0005_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDiscount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount_amount', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_discounts', to='bookings.booking')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_discounts', to='gyms.discount')),
            ],
            options={
                'verbose_name': 'Booking Discount',
                'verbose_name_plural': 'Booking Discounts',
                'db_table': 'booking_discounts',
            },
        ),
    ]
