# Generated by Django 6.0.2 on 2026-03-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_bookingdiscount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
