# Generated by Django 6.0.2 on 2026-03-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(
                condition=models.Q(start_time__lt=models.F('end_time')),
                name='booking_start_before_end_check',
            ),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(
                condition=models.Q(status__in=['pending', 'confirmed']),
                fields=('field', 'booking_date', 'start_time', 'end_time'),
                name='booking_exact_active_interval_unique',
            ),
        ),
        migrations.CreateModel(
            name='BookingIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Idempotency Key',
                'verbose_name_plural': 'Booking Idempotency Keys',
                'db_table': 'booking_idempotency_keys',
            },
        ),
        migrations.AddConstraint(
            model_name='bookingidempotencykey',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='booking_idempotency_user_key_unique'),
        ),
    ]
