# Generated by Django 6.0.2 on 2026-03-10

from django.db import migrations


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_idempotency_and_constraints'),
    ]

    operations = [
        migrations.RunPython(
            noop,
            reverse_code=noop,
        ),
    ]
