# Generated by Cursor on 2026-03-30

from django.db import migrations, models
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_postgres_overlap_exclusion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingdiscount",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[MinValueValidator(0)],
            ),
        ),
    ]

