# Generated by ChatGPT on 2026-04-18

from datetime import datetime

from django.db import migrations, models
from django.utils import timezone


def populate_booking_interval_datetimes(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    db_alias = schema_editor.connection.alias
    default_timezone = timezone.get_default_timezone()

    bookings_to_update = []
    for booking in Booking.objects.using(db_alias).all().iterator():
        if not booking.booking_date or not booking.start_time or not booking.end_time:
            continue

        booking.start_datetime = timezone.make_aware(
            datetime.combine(booking.booking_date, booking.start_time),
            default_timezone,
        )
        booking.end_datetime = timezone.make_aware(
            datetime.combine(booking.booking_date, booking.end_time),
            default_timezone,
        )
        bookings_to_update.append(booking)

    if bookings_to_update:
        Booking.objects.using(db_alias).bulk_update(bookings_to_update, ['start_datetime', 'end_datetime'])


def create_postgres_overlap_exclusion(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'booking_active_overlap_excl'
            ) THEN
                ALTER TABLE bookings
                DROP CONSTRAINT booking_active_overlap_excl;
            END IF;

            ALTER TABLE bookings
            ADD CONSTRAINT booking_active_overlap_excl
            EXCLUDE USING gist (
                field_id WITH =,
                tstzrange(start_datetime, end_datetime, '[)') WITH &&
            )
            WHERE (status IN ('pending', 'confirmed'));
        END$$;
        """
    )


def drop_postgres_overlap_exclusion(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    schema_editor.execute(
        """
        ALTER TABLE bookings
        DROP CONSTRAINT IF EXISTS booking_active_overlap_excl;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingdiscount_decimal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_booking_interval_datetimes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(editable=False),
        ),
        migrations.RunPython(
            create_postgres_overlap_exclusion,
            reverse_code=drop_postgres_overlap_exclusion,
        ),
    ]
