#!/usr/bin/env python
"""
Requirements Generator Script
==============================
This script helps generate and manage requirements for the Futsal backend project.

Usage:
    python setup_requirements.py --generate      # Generate from current environment
    python setup_requirements.py --pipreqs       # Generate using pipreqs
    python setup_requirements.py --check         # Check for outdated packages
"""

import argparse
import subprocess
import sys
import os
from pathlib import Path


def run_command(command, description):
    """Run a shell command and display the result."""
    print(f"\n{'='*60}")
    print(f"Running: {description}")
    print(f"Command: {command}")
    print('='*60)
    
    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True
        )
        print(result.stdout)
        if result.stderr:
            print("STDERR:", result.stderr)
        return result.returncode == 0
    except Exception as e:
        print(f"Error: {e}")
        return False


def generate_pip_freeze():
    """Generate requirements using pip freeze."""
    output_file = Path(__file__).parent / "requirements-generated.txt"
    
    print(f"\nGenerating requirements using 'pip freeze'...")
    print(f"Output file: {output_file}")
    
    # Get current directory
    script_dir = Path(__file__).parent
    os.chdir(script_dir)
    
    success = run_command(
        "pip freeze",
        "Pip freeze (showing all installed packages)"
    )
    
    # Save to file
    result = subprocess.run(
        "pip freeze",
        shell=True,
        capture_output=True,
        text=True
    )
    
    with open(output_file, 'w') as f:
        f.write("# Generated by pip freeze\n")
        f.write("# " + "="*56 + "\n")
        f.write("# Run: pip install -r requirements-generated.txt\n")
        f.write("# " + "="*56 + "\n\n")
        f.write(result.stdout)
    
    print(f"\n✓ Requirements saved to: {output_file}")
    return True


def generate_pipreqs():
    """Generate requirements using pipreqs (analyzes code imports)."""
    script_dir = Path(__file__).parent
    
    # First install pipreqs
    print("\nInstalling pipreqs...")
    run_command("pip install pipreqs", "Installing pipreqs")
    
    output_file = script_dir / "requirements-pipreqs.txt"
    
    print(f"\nGenerating requirements using 'pipreqs'...")
    print(f"Analyzing imports in: {script_dir}")
    
    # Run pipreqs
    result = subprocess.run(
        f"pipreqs {script_dir} --force --output-file {output_file}",
        shell=True,
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        print(f"\n✓ Requirements saved to: {output_file}")
        print(result.stdout)
        return True
    else:
        print(f"Error: {result.stderr}")
        return False


def check_outdated():
    """Check for outdated packages."""
    print("\nChecking for outdated packages...")
    print("="*60)
    
    result = subprocess.run(
        "pip list --outdated",
        shell=True,
        capture_output=True,
        text=True
    )
    
    print(result.stdout)
    
    if "WARNING" in result.stdout or not result.stdout.strip():
        print("\nNo outdated packages found or pip list not available.")
    else:
        print("\nTo update packages, run:")
        print("  pip install --upgrade <package_name>")
        print("\nOr update all at once:")
        print("  pip install --upgrade -r requirements.txt")
    
    return True


def create_venv():
    """Create a virtual environment."""
    script_dir = Path(__file__).parent
    venv_path = script_dir / "venv"
    
    print(f"\nCreating virtual environment at: {venv_path}")
    
    result = subprocess.run(
        f"python -m venv {venv_path}",
        shell=True,
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        print(f"\n✓ Virtual environment created!")
        print(f"\nTo activate:")
        print(f"  Windows: {venv_path}\\Scripts\\activate")
        print(f"  Linux/Mac: source {venv_path}/bin/activate")
        return True
    else:
        print(f"Error: {result.stderr}")
        return False


def install_requirements(req_file="requirements.txt"):
    """Install requirements from a file."""
    print(f"\nInstalling requirements from: {req_file}")
    
    script_dir = Path(__file__).parent
    req_path = script_dir / req_file
    
    if not req_path.exists():
        print(f"Error: {req_file} not found!")
        return False
    
    result = subprocess.run(
        f"pip install -r {req_path}",
        shell=True,
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        print(f"\n✓ Requirements installed successfully!")
        return True
    else:
        print(f"Error: {result.stderr}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Requirements Generator for Futsal Backend",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python setup_requirements.py --generate    Generate from pip freeze
    python setup_requirements.py --pipreqs      Generate from code analysis
    python setup_requirements.py --check        Check outdated packages
    python setup_requirements.py --install      Install requirements.txt
    python setup_requirements.py --venv          Create virtual environment
        """
    )
    
    parser.add_argument(
        "--generate", 
        action="store_true", 
        help="Generate requirements using pip freeze"
    )
    parser.add_argument(
        "--pipreqs", 
        action="store_true", 
        help="Generate requirements using pipreqs (analyzes code)"
    )
    parser.add_argument(
        "--check", 
        action="store_true", 
        help="Check for outdated packages"
    )
    parser.add_argument(
        "--install", 
        action="store_true", 
        help="Install requirements.txt"
    )
    parser.add_argument(
        "--venv", 
        action="store_true", 
        help="Create virtual environment"
    )
    parser.add_argument(
        "--all", 
        action="store_true", 
        help="Run all generation methods"
    )
    
    args = parser.parse_args()
    
    if not any(vars(args).values()):
        parser.print_help()
        print("\n" + "="*60)
        print("Quick Start Guide:")
        print("="*60)
        print("""
1. Create a virtual environment:
   python setup_requirements.py --venv

2. Activate the virtual environment:
   Windows: venv\\Scripts\\activate
   Linux/Mac: source venv/bin/activate

3. Install requirements:
   python setup_requirements.py --install

4. Check for outdated packages:
   python setup_requirements.py --check

5. Generate requirements (two methods):
   - pip freeze (captures ALL packages):
     python setup_requirements.py --generate
   - pipreqs (analyzes code imports):
     python setup_requirements.py --pipreqs
        """)
        return
    
    if args.generate or args.all:
        generate_pip_freeze()
    
    if args.pipreqs or args.all:
        generate_pipreqs()
    
    if args.check or args.all:
        check_outdated()
    
    if args.install:
        install_requirements()
    
    if args.venv:
        create_venv()


if __name__ == "__main__":
    main()
